type PropDef = {
  name: string;
  type: string;
  default?: string;
  description: string;
};

export const propsRegistry: Record<string, PropDef[]> = {
  "accordion": [
    { name: "multiple", type: "boolean", default: "false", description: "Whether multiple items can be open at the same time" },
    { name: "defaultValue", type: "(any | null)[]", description: "The value of the item(s) to expand by default (array)" },
    { name: "value", type: "(any | null)[]", description: "The controlled value of the item(s) to expand (array)" },
    { name: "onValueChange", type: "(value: (any | null)[], eventDetails) => void", description: "Callback fired when the expanded state changes" },
    { name: "disabled", type: "boolean", default: "false", description: "When true, prevents the user from interacting with the accordion" },
  ],
  "alert-dialog": [
    { name: "open", type: "boolean", description: "The controlled open state of the alert dialog" },
    { name: "onOpenChange", type: "(open: boolean) => void", description: "Callback fired when the open state changes" },
    { name: "children", type: "React.ReactNode", description: "The trigger element and dialog content" },
  ],
  "autocomplete-root": [
    { name: "items", type: "T[] | GroupedItems[]", description: "The items to display. Can be a flat array or an array of groups (objects with value and items properties)." },
    { name: "mode", type: "'list' | 'both' | 'inline' | 'none'", default: "'list'", description: "Controls filtering and inline autocompletion. 'list' filters items, 'both' filters and shows inline completion, 'inline' shows inline completion without filtering, 'none' disables both." },
    { name: "openOnInputClick", type: "boolean", default: "false", description: "Whether the popup opens when clicking the input." },
    { name: "value", type: "string", description: "The controlled input value." },
    { name: "defaultValue", type: "string", description: "The uncontrolled initial input value." },
    { name: "onValueChange", type: "(value: string, eventDetails) => void", description: "Callback fired when the input value changes." },
    { name: "onOpenChange", type: "(open: boolean, eventDetails) => void", description: "Callback fired when the popup is opened or closed." },
    { name: "autoHighlight", type: "boolean | 'always'", default: "false", description: "Whether the first matching item is highlighted automatically." },
    { name: "keepHighlight", type: "boolean", default: "false", description: "Whether the highlighted item is preserved when the pointer leaves the list." },
    { name: "disabled", type: "boolean", default: "false", description: "Whether the component should ignore user interaction." },
  ],
  "autocomplete-item": [
    { name: "value", type: "any", description: "The value of the item. Required." },
    { name: "inset", type: "boolean", default: "false", description: "Adds additional left padding for nested item layouts." },
  ],
  "autocomplete-group": [
    { name: "items", type: "any[]", description: "Items to be rendered within this group. Child Collection components will use these items." },
  ],
  "autocomplete-other": [
    { name: "AutocompleteContent.portal", type: "boolean", default: "true", description: "Whether to render in a portal. Set to false inside Dialog or Drawer." },
    { name: "AutocompleteTrigger.children", type: "React.ReactNode", description: "Optional custom trigger content. Defaults to a chevron icon." },
    { name: "AutocompleteClear.children", type: "React.ReactNode", description: "Optional custom clear content. Defaults to an X icon." },
  ],
  "avatar": [
    { name: "size", type: "'sm' | 'md' | 'lg'", default: "'md'", description: "The size of the avatar" },
    { name: "src", type: "string", description: "The image source URL for the avatar" },
    { name: "alt", type: "string", description: "Alternative text for the avatar image" },
    { name: "fallback", type: "React.ReactNode", description: "Content to display when the image fails to load or is not provided" },
  ],
  "badge": [
    { name: "variant", type: "'default' | 'secondary' | 'destructive' | 'outline' | 'success' | 'warning' | 'info'", default: "'default'", description: "The visual style variant of the badge" },
    { name: "size", type: "'sm' | 'default' | 'lg'", default: "'default'", description: "The size of the badge" },
    { name: "rounded", type: "'default' | 'sm' | 'md' | 'lg' | 'none'", default: "'default'", description: "The border radius of the badge" },
    { name: "render", type: "ReactElement", description: "Custom render prop for composition (Base UI pattern)" },
    { name: "interactive", type: "boolean", default: "false", description: "Whether the badge should be interactive (clickable)" },
    { name: "icon", type: "ReactNode", description: "Icon to display before the content" },
    { name: "dismissible", type: "boolean", default: "false", description: "Whether to show a close button" },
    { name: "onDismiss", type: "() => void", description: "Callback when close button is clicked" },
  ],
  "button": [
    { name: "variant", type: "'default' | 'destructive' | 'outline' | 'secondary' | 'ghost' | 'link'", default: "'default'", description: "The visual style variant of the button" },
    { name: "size", type: "'default' | 'sm' | 'lg' | 'icon'", default: "'default'", description: "The size of the button" },
    { name: "render", type: "ReactElement | ((props, state) => ReactElement)", default: "undefined", description: "Replace the rendered element with a different tag or component." },
  ],
  "card": [
    { name: "className", type: "string", description: "Additional CSS classes to apply to the card" },
  ],
  "checkbox-group": [
    { name: "value", type: "string[]", description: "The controlled value of the checkbox group" },
    { name: "defaultValue", type: "string[]", default: "[]", description: "The default value when uncontrolled" },
    { name: "onValueChange", type: "(value: string[]) => void", description: "Callback fired when the group value changes" },
    { name: "disabled", type: "boolean", default: "false", description: "Whether the entire checkbox group is disabled" },
    { name: "required", type: "boolean", default: "false", description: "Whether at least one checkbox must be checked" },
  ],
  "checkbox": [
    { name: "checked", type: "boolean | 'indeterminate'", description: "The controlled checked state of the checkbox" },
    { name: "defaultChecked", type: "boolean", default: "false", description: "The default checked state when uncontrolled" },
    { name: "onCheckedChange", type: "(checked: boolean | 'indeterminate') => void", description: "Callback fired when the checked state changes" },
    { name: "disabled", type: "boolean", default: "false", description: "Whether the checkbox is disabled" },
    { name: "required", type: "boolean", default: "false", description: "Whether the checkbox is required" },
  ],
  "collapsible": [
    { name: "open", type: "boolean", description: "The controlled open state of the collapsible" },
    { name: "defaultOpen", type: "boolean", default: "false", description: "The initial open state when uncontrolled" },
    { name: "onOpenChange", type: "(open: boolean) => void", description: "Callback fired when the open state changes" },
    { name: "disabled", type: "boolean", default: "false", description: "When true, prevents the user from interacting with the collapsible" },
  ],
  "combobox-root": [
    { name: "items", type: "T[] | GroupedItems[]", description: "The items to display. Can be a flat array or an array of groups (objects with value and items properties). Required for filtering to work." },
    { name: "openOnInputClick", type: "boolean", default: "false", description: "Whether the popup opens when clicking the input." },
    { name: "value", type: "any", description: "The controlled selected value." },
    { name: "defaultValue", type: "any", description: "The uncontrolled initial selected value." },
    { name: "onValueChange", type: "(value: any, eventDetails) => void", description: "Callback fired when the selected value changes." },
    { name: "onInputValueChange", type: "(value: string, eventDetails) => void", description: "Callback fired when the input text changes." },
    { name: "onOpenChange", type: "(open: boolean, eventDetails) => void", description: "Callback fired when the popup is opened or closed." },
    { name: "multiple", type: "boolean", default: "false", description: "Whether multiple items can be selected." },
    { name: "disabled", type: "boolean", default: "false", description: "Whether the component should ignore user interaction." },
  ],
  "combobox-item": [
    { name: "value", type: "any", description: "The value of the item. Required." },
    { name: "inset", type: "boolean", default: "false", description: "Adds extra left padding for grouped or nested option content." },
  ],
  "combobox-group": [
    { name: "items", type: "any[]", description: "Items to be rendered within this group. Child Collection components will use these items." },
  ],
  "combobox-other": [
    { name: "ComboboxContent.portal", type: "boolean", default: "true", description: "Whether to render in a portal. Set to false inside Dialog or Drawer." },
    { name: "ComboboxTrigger.children", type: "React.ReactNode", description: "Optional trigger content. Defaults to a chevron icon." },
    { name: "ComboboxClear.children", type: "React.ReactNode", description: "Optional clear action content. Defaults to an X icon." },
  ],
  "context-menu": [
    { name: "defaultOpen", type: "boolean", default: "false", description: "The initial open state when uncontrolled" },
    { name: "open", type: "boolean", description: "The controlled open state of the context menu" },
    { name: "onOpenChange", type: "(open: boolean) => void", description: "Callback fired when the open state changes" },
    { name: "disabled", type: "boolean", default: "false", description: "When true, prevents the context menu from opening" },
    { name: "children", type: "React.ReactNode", description: "The trigger element and menu content" },
  ],
  "dialog": [
    { name: "open", type: "boolean", description: "The controlled open state of the dialog" },
    { name: "onOpenChange", type: "(open: boolean) => void", description: "Callback fired when the open state changes" },
  ],
  "drawer": [
    { name: "open", type: "boolean", description: "The controlled open state of the drawer root." },
    { name: "defaultOpen", type: "boolean", default: "false", description: "The initial open state for uncontrolled usage." },
    { name: "onOpenChange", type: "(open: boolean) => void", description: "Callback fired when the drawer open state changes." },
    { name: "DrawerContent.side", type: "'top' | 'right' | 'bottom' | 'left'", default: "'right'", description: "Controls which side the drawer enters from." },
  ],
  "field": [
    { name: "name", type: "string", description: "The name of the field (required)" },
    { name: "disabled", type: "boolean", default: "false", description: "Whether the field is disabled" },
    { name: "invalid", type: "boolean", default: "false", description: "Whether the field is in an invalid state" },
    { name: "required", type: "boolean", default: "false", description: "Whether the field is required" },
    { name: "validate", type: "(value: any) => string | undefined", description: "Custom validation function that returns an error message or undefined" },
  ],
  "fieldset": [
    { name: "children", type: "React.ReactNode", description: "Field controls and optional descriptive content." },
    { name: "disabled", type: "boolean", default: "false", description: "Disables the grouped form controls when supported by child controls." },
    { name: "FieldsetLegend.children", type: "React.ReactNode", description: "Accessible label for the grouped controls." },
  ],
  "form": [
    { name: "errors", type: "Record<string, string | string[]>", default: "{}", description: "Object keyed by field name with validation messages." },
    { name: "onClearErrors", type: "(errors: Record<string, string | string[]>) => void", description: "Callback fired when errors should be cleared." },
    { name: "onSubmit", type: "(event: React.FormEvent<HTMLFormElement>) => void", description: "Form submit handler." },
    { name: "render", type: "React.ReactElement | ((props, state) => React.ReactElement)", default: "<form />", description: "Optional custom render element using Base UI's render pattern." },
  ],
  "input": [
    { name: "type", type: "string", default: "'text'", description: "The type of the input field" },
    { name: "placeholder", type: "string", description: "Placeholder text displayed when the input is empty" },
    { name: "disabled", type: "boolean", default: "false", description: "Whether the input is disabled" },
  ],
  "menu": [
    { name: "open", type: "boolean", description: "The controlled open state of the menu root." },
    { name: "defaultOpen", type: "boolean", default: "false", description: "The initial open state for uncontrolled usage." },
    { name: "onOpenChange", type: "(open: boolean) => void", description: "Callback fired when the menu open state changes." },
    { name: "MenuItem.inset", type: "boolean", default: "false", description: "Adds indentation for nested command-style layouts." },
    { name: "MenuLabel.inset", type: "boolean", default: "false", description: "Adds indentation to section labels." },
    { name: "MenuSubTrigger.inset", type: "boolean", default: "false", description: "Adds indentation to submenu triggers." },
  ],
  "menubar": [
    { name: "value", type: "string", description: "The controlled value of the currently active menu" },
    { name: "defaultValue", type: "string", description: "The value of the menu to activate by default" },
    { name: "onValueChange", type: "(value: string) => void", description: "Callback fired when the active menu changes" },
    { name: "disabled", type: "boolean", default: "false", description: "When true, prevents the user from interacting with the menubar" },
    { name: "dir", type: "'ltr' | 'rtl'", default: "'ltr'", description: "The reading direction of the menubar" },
  ],
  "meter": [
    { name: "value", type: "number", description: "The current measured value." },
    { name: "min", type: "number", default: "0", description: "The minimum value of the measurement range." },
    { name: "max", type: "number", default: "100", description: "The maximum value of the measurement range." },
    { name: "MeterValue.children", type: "React.ReactNode", description: "Optional custom rendered textual value." },
  ],
  "navigation-menu": [
    { name: "value", type: "string", description: "The controlled value of the currently active menu item" },
    { name: "defaultValue", type: "string", description: "The value of the menu item to activate by default" },
    { name: "onValueChange", type: "(value: string) => void", description: "Callback fired when the active menu item changes" },
    { name: "disabled", type: "boolean", default: "false", description: "When true, prevents the user from interacting with the navigation menu" },
    { name: "dir", type: "'ltr' | 'rtl'", default: "'ltr'", description: "The reading direction of the navigation menu" },
    { name: "orientation", type: "'horizontal' | 'vertical'", default: "'horizontal'", description: "The orientation of the navigation menu" },
  ],
  "number-field": [
    { name: "value", type: "number", description: "The controlled numeric value." },
    { name: "defaultValue", type: "number", description: "Initial numeric value when uncontrolled." },
    { name: "onValueChange", type: "(value: number | null) => void", description: "Callback fired when the numeric value changes." },
    { name: "min", type: "number", description: "Minimum allowed value." },
    { name: "max", type: "number", description: "Maximum allowed value." },
    { name: "step", type: "number", default: "1", description: "Increment/decrement step size." },
  ],
  "popover": [
    { name: "defaultOpen", type: "boolean", default: "false", description: "The initial open state when uncontrolled." },
    { name: "open", type: "boolean", description: "The controlled open state of the popover." },
    { name: "onOpenChange", type: "(open: boolean) => void", description: "Callback fired when the open state changes." },
    { name: "PopoverContent.portal", type: "boolean", default: "true", description: "Whether to render in a portal. Set to false inside Dialog or Drawer." },
    { name: "PopoverContent.side", type: "'top' | 'right' | 'bottom' | 'left'", default: "'bottom'", description: "Preferred side for the popover popup." },
    { name: "PopoverContent.align", type: "'start' | 'center' | 'end'", default: "'center'", description: "Preferred alignment relative to the trigger." },
    { name: "PopoverContent.sideOffset", type: "number", default: "8", description: "Distance in pixels between trigger and popup." },
  ],
  "preview-card": [
    { name: "openDelay", type: "number", default: "700", description: "The delay in milliseconds before the preview card opens" },
    { name: "closeDelay", type: "number", default: "300", description: "The delay in milliseconds before the preview card closes" },
    { name: "open", type: "boolean", description: "The controlled open state of the preview card" },
    { name: "onOpenChange", type: "(open: boolean) => void", description: "Callback fired when the open state changes" },
    { name: "side", type: "'top' | 'right' | 'bottom' | 'left'", default: "'bottom'", description: "The preferred side of the trigger to render the preview card" },
    { name: "sideOffset", type: "number", default: "8", description: "The distance in pixels from the trigger" },
  ],
  "progress": [
    { name: "value", type: "number", description: "The current progress value." },
    { name: "max", type: "number", default: "100", description: "The maximum value that represents full completion." },
    { name: "getValueLabel", type: "(value: number, max: number) => string", description: "Optional formatter for accessible progress value text." },
  ],
  "radio": [
    { name: "RadioGroup.value", type: "string", description: "The controlled selected radio value." },
    { name: "RadioGroup.defaultValue", type: "string", description: "The initially selected value when uncontrolled." },
    { name: "RadioGroup.onValueChange", type: "(value: string) => void", description: "Callback fired when the selected value changes." },
    { name: "Radio.disabled", type: "boolean", default: "false", description: "Disables a radio option." },
    { name: "Radio.required", type: "boolean", default: "false", description: "Marks a radio option as required." },
  ],
  "scroll-area": [
    { name: "ScrollAreaScrollbar.orientation", type: "'vertical' | 'horizontal'", default: "'vertical'", description: "Sets scrollbar orientation." },
    { name: "type", type: "'hover' | 'scroll' | 'auto' | 'always'", default: "'hover'", description: "Controls when scrollbars are visible." },
    { name: "scrollHideDelay", type: "number", default: "600", description: "Delay before auto-hidden scrollbars are hidden again." },
  ],
  "select": [
    { name: "value", type: "string", description: "The controlled selected value." },
    { name: "defaultValue", type: "string", description: "The initially selected value when uncontrolled." },
    { name: "onValueChange", type: "(value: string) => void", description: "Callback fired when selection changes." },
    { name: "SelectContent.portal", type: "boolean", default: "true", description: "Whether to render the dropdown in a portal. Set to false when used inside a Dialog or Drawer to keep it within the modal focus trap." },
    { name: "SelectContent.position", type: "'item-aligned' | 'popper'", default: "'popper'", description: "Controls popup positioning strategy." },
    { name: "SelectContent.sideOffset", type: "number", default: "4", description: "Distance between trigger and popup." },
    { name: "SelectItem.showIndicator", type: "boolean", default: "false", description: "Shows a selection indicator icon for selected items." },
    { name: "SelectItem.indicatorPosition", type: "'left' | 'right'", default: "'left'", description: "Positions the selection indicator." },
  ],
  "separator": [
    { name: "orientation", type: "'horizontal' | 'vertical'", default: "'horizontal'", description: "Sets the separator orientation." },
    { name: "decorative", type: "boolean", default: "true", description: "Whether the separator is decorative only." },
  ],
  "slider": [
    { name: "value", type: "number[]", description: "The controlled value of the slider" },
    { name: "defaultValue", type: "number[]", description: "The default value when uncontrolled" },
    { name: "onValueChange", type: "(value: number[]) => void", description: "Callback fired when the slider value changes" },
    { name: "min", type: "number", default: "0", description: "The minimum allowed value" },
    { name: "max", type: "number", default: "100", description: "The maximum allowed value" },
    { name: "step", type: "number", default: "1", description: "The step increment between values" },
    { name: "disabled", type: "boolean", default: "false", description: "Whether the slider is disabled" },
    { name: "orientation", type: "'horizontal' | 'vertical'", default: "'horizontal'", description: "The orientation of the slider" },
  ],
  "switch": [
    { name: "checked", type: "boolean", description: "The controlled checked state." },
    { name: "defaultChecked", type: "boolean", default: "false", description: "The initial checked state when uncontrolled." },
    { name: "onCheckedChange", type: "(checked: boolean) => void", description: "Callback fired when checked state changes." },
    { name: "disabled", type: "boolean", default: "false", description: "Disables the switch." },
    { name: "required", type: "boolean", default: "false", description: "Marks the switch as required in a form." },
  ],
  "tabs": [
    { name: "defaultValue", type: "string", description: "The value of the tab to select by default" },
    { name: "value", type: "string", description: "The controlled value of the currently active tab" },
    { name: "onValueChange", type: "(value: string) => void", description: "Callback fired when the active tab changes" },
  ],
  "toast": [
    { name: "Toast.limit", type: "number", default: "3", description: "Maximum number of visible toasts" },
    { name: "Toast.timeout", type: "number", default: "5000", description: "Auto-dismiss timeout in milliseconds. Use 0 to prevent auto-dismiss." },
    { name: "Toast.toastManager", type: "ToastManager", description: "External toast manager created via createToastManager() for global usage" },
    { name: "ToastRoot.variant", type: "'default' | 'destructive' | 'success' | 'warning' | 'loading'", default: "'default'", description: "The visual style variant of the toast" },
    { name: "ToastRoot.toast", type: "ToastObject", description: "The toast data object from the manager (required)" },
    { name: "ToastRoot.swipeDirection", type: "Array<'up' | 'down' | 'left' | 'right'>", default: "['down', 'right']", description: "The directions in which the toast can be swiped to dismiss" },
    { name: "manager.add()", type: "(options: { title?, description?, type?, timeout?, actionProps?, priority? }) => string", description: "Creates a toast notification and returns its ID" },
    { name: "manager.update()", type: "(id: string, updates) => void", description: "Updates an existing toast's title, description, type, timeout, or actionProps" },
    { name: "manager.promise()", type: "(promise, { loading, success, error }) => Promise", description: "Binds a promise to a toast that auto-transitions through loading, success, and error states" },
    { name: "manager.close()", type: "(id: string) => void", description: "Closes a toast by its ID" },
  ],
  "toggle-group": [
    { name: "type", type: "'single' | 'multiple'", default: "'single'", description: "Selection mode for the toggle group." },
    { name: "value", type: "string | string[]", description: "Controlled selected value(s)." },
    { name: "defaultValue", type: "string | string[]", description: "Initial value(s) for uncontrolled usage." },
    { name: "onValueChange", type: "(value: string | string[]) => void", description: "Callback fired when selection changes." },
    { name: "ToggleGroupItem.variant", type: "'default' | 'outline'", default: "'outline'", description: "Visual style variant for each item." },
    { name: "ToggleGroupItem.size", type: "'default' | 'sm' | 'lg'", default: "'sm'", description: "Size variant for each item." },
  ],
  "toggle": [
    { name: "variant", type: "'default' | 'outline'", default: "'default'", description: "The visual style variant of the toggle" },
    { name: "size", type: "'default' | 'sm' | 'lg'", default: "'default'", description: "The size of the toggle" },
    { name: "pressed", type: "boolean", description: "The controlled pressed state of the toggle" },
    { name: "defaultPressed", type: "boolean", default: "false", description: "The default pressed state when uncontrolled" },
    { name: "onPressedChange", type: "(pressed: boolean) => void", description: "Callback fired when the pressed state changes" },
    { name: "disabled", type: "boolean", default: "false", description: "Whether the toggle is disabled" },
  ],
  "toolbar": [
    { name: "orientation", type: "'horizontal' | 'vertical'", default: "'horizontal'", description: "The orientation of the toolbar" },
    { name: "dir", type: "'ltr' | 'rtl'", default: "'ltr'", description: "The reading direction of the toolbar" },
    { name: "loop", type: "boolean", default: "true", description: "Whether keyboard navigation should loop from last to first and vice versa" },
  ],
  "tooltip": [
    { name: "variant", type: "'default' | 'inverse'", default: "'default'", description: "The visual style variant of the tooltip" },
    { name: "openDelay", type: "number", default: "700", description: "The delay in milliseconds before the tooltip opens" },
    { name: "closeDelay", type: "number", default: "300", description: "The delay in milliseconds before the tooltip closes" },
    { name: "side", type: "'top' | 'right' | 'bottom' | 'left'", default: "'top'", description: "The preferred side of the trigger to render the tooltip" },
    { name: "sideOffset", type: "number", default: "4", description: "The distance in pixels from the trigger" },
    { name: "showArrow", type: "boolean", default: "true", description: "Whether to show the tooltip arrow pointing to the trigger" },
  ],
};
