type PropDef = {
  name: string;
  type: string;
  default?: string;
  description: string;
};

export const propsRegistry: Record<string, PropDef[]> = {
  "accordion-root": [
    { name: "multiple", type: "boolean", default: "false", description: "Whether multiple items can be open at the same time" },
    { name: "defaultValue", type: "(any | null)[]", description: "The value of the item(s) to expand by default (array)" },
    { name: "value", type: "(any | null)[]", description: "The controlled value of the item(s) to expand (array)" },
    { name: "onValueChange", type: "(value: (any | null)[], eventDetails) => void", description: "Callback fired when the expanded state changes" },
    { name: "disabled", type: "boolean", default: "false", description: "When true, prevents the user from interacting with the accordion" },
    { name: "loopFocus", type: "boolean", default: "true", description: "Loops focus from the last trigger back to the first when using arrow key navigation" },
    { name: "keepMounted", type: "boolean", default: "false", description: "Keeps closed panels mounted in the DOM. Can also be set on AccordionPanel for per-panel control" },
    { name: "hiddenUntilFound", type: "boolean", default: "false", description: "Allows browser find-in-page to reveal matching closed panel content using hidden='until-found'" },
    { name: "orientation", type: "'vertical' | 'horizontal'", default: "'vertical'", description: "Sets the keyboard navigation axis. Dinachi's bundled styles are optimized for vertical accordions" },
  ],
  "accordion-item": [
    { name: "value", type: "any", description: "Unique value for the item. If omitted, Base UI generates one automatically" },
    { name: "disabled", type: "boolean", default: "false", description: "Disables a single item while leaving the rest of the accordion interactive" },
    { name: "onOpenChange", type: "(open: boolean, eventDetails) => void", description: "Fires when the individual item's panel opens or closes" },
  ],
  "accordion-panel": [
    { name: "keepMounted", type: "boolean", default: "false", description: "Keeps this specific panel mounted when closed so uncontrolled field state is preserved" },
    { name: "hiddenUntilFound", type: "boolean", default: "false", description: "Lets browser find-in-page reveal this panel even while it is visually hidden" },
  ],
  "alert-dialog": [
    { name: "open", type: "boolean", description: "The controlled open state of the alert dialog." },
    { name: "defaultOpen", type: "boolean", default: "false", description: "The initial open state for uncontrolled usage." },
    { name: "onOpenChange", type: "(open: boolean) => void", description: "Callback fired when the open state changes." },
    { name: "AlertDialogPopup.initialFocus", type: "boolean | RefObject | function", description: "Element to focus when the dialog opens." },
    { name: "AlertDialogPopup.finalFocus", type: "boolean | RefObject | function", description: "Element to focus when the dialog closes." },
  ],
  "autocomplete-root": [
    { name: "items", type: "T[] | GroupedItems[]", description: "The items to display. Can be a flat array or an array of groups (objects with value and items properties)." },
    { name: "mode", type: "'list' | 'both' | 'inline' | 'none'", default: "'list'", description: "Controls filtering and inline autocompletion. 'list' filters items, 'both' filters and shows inline completion, 'inline' shows inline completion without filtering, 'none' disables both." },
    { name: "openOnInputClick", type: "boolean", default: "false", description: "Whether the popup opens when clicking the input." },
    { name: "value", type: "string", description: "The controlled input value." },
    { name: "defaultValue", type: "string", description: "The uncontrolled initial input value." },
    { name: "onValueChange", type: "(value: string, eventDetails) => void", description: "Callback fired when the input value changes." },
    { name: "onOpenChange", type: "(open: boolean, eventDetails) => void", description: "Callback fired when the popup is opened or closed." },
    { name: "autoHighlight", type: "boolean | 'always'", default: "false", description: "Whether the first matching item is highlighted automatically." },
    { name: "keepHighlight", type: "boolean", default: "false", description: "Whether the highlighted item is preserved when the pointer leaves the list." },
    { name: "disabled", type: "boolean", default: "false", description: "Whether the component should ignore user interaction." },
  ],
  "autocomplete-item": [
    { name: "value", type: "any", description: "The value of the item. Required." },
    { name: "inset", type: "boolean", default: "false", description: "Adds additional left padding for nested item layouts." },
  ],
  "autocomplete-group": [
    { name: "items", type: "any[]", description: "Items to be rendered within this group. Child Collection components will use these items." },
  ],
  "autocomplete-other": [
    { name: "AutocompleteContent.portal", type: "boolean", default: "true", description: "Whether to render in a portal. Set to false inside Dialog or Drawer." },
    { name: "AutocompleteTrigger.children", type: "React.ReactNode", description: "Optional custom trigger content. Defaults to a chevron icon." },
    { name: "AutocompleteClear.children", type: "React.ReactNode", description: "Optional custom clear content. Defaults to an X icon." },
  ],
  "avatar": [
    { name: "size", type: "'sm' | 'md' | 'lg'", default: "'md'", description: "The size of the avatar" },
    { name: "src", type: "string", description: "The image source URL for the avatar" },
    { name: "alt", type: "string", description: "Alternative text for the avatar image" },
    { name: "fallback", type: "React.ReactNode", description: "Content to display when the image fails to load or is not provided" },
  ],
  "badge": [
    { name: "variant", type: "'default' | 'secondary' | 'destructive' | 'outline' | 'success' | 'warning' | 'info'", default: "'default'", description: "The visual style variant of the badge." },
    { name: "size", type: "'sm' | 'default' | 'lg'", default: "'default'", description: "The size of the badge." },
    { name: "rounded", type: "'default' | 'sm' | 'md' | 'lg' | 'none'", default: "'default'", description: "The border radius of the badge." },
    { name: "icon", type: "ReactNode", description: "Icon to display before the content." },
    { name: "dismissible", type: "boolean", default: "false", description: "Whether to show a close button." },
    { name: "onDismiss", type: "() => void", description: "Callback when close button is clicked." },
  ],
  "button": [
    { name: "variant", type: "'default' | 'destructive' | 'outline' | 'secondary' | 'ghost' | 'link'", default: "'default'", description: "The visual style variant of the button" },
    { name: "size", type: "'default' | 'sm' | 'lg' | 'icon'", default: "'default'", description: "The size of the button" },
    { name: "render", type: "ReactElement | ((props, state) => ReactElement)", default: "undefined", description: "Replace the rendered element with a different tag or component." },
  ],
  "card": [
    { name: "className", type: "string", description: "Additional CSS classes to apply to the card" },
  ],
  "checkbox-group": [
    { name: "value", type: "string[]", description: "The controlled value of the checkbox group" },
    { name: "defaultValue", type: "string[]", default: "[]", description: "The default value when uncontrolled" },
    { name: "onValueChange", type: "(value: string[]) => void", description: "Callback fired when the group value changes" },
    { name: "disabled", type: "boolean", default: "false", description: "Whether the entire checkbox group is disabled" },
    { name: "required", type: "boolean", default: "false", description: "Whether at least one checkbox must be checked" },
  ],
  "checkbox": [
    { name: "checked", type: "boolean | 'indeterminate'", description: "The controlled checked state of the checkbox" },
    { name: "defaultChecked", type: "boolean", default: "false", description: "The default checked state when uncontrolled" },
    { name: "onCheckedChange", type: "(checked: boolean | 'indeterminate') => void", description: "Callback fired when the checked state changes" },
    { name: "disabled", type: "boolean", default: "false", description: "Whether the checkbox is disabled" },
    { name: "required", type: "boolean", default: "false", description: "Whether the checkbox is required" },
  ],
  "collapsible": [
    { name: "open", type: "boolean", description: "The controlled open state of the collapsible" },
    { name: "defaultOpen", type: "boolean", default: "false", description: "The initial open state when uncontrolled" },
    { name: "onOpenChange", type: "(open: boolean) => void", description: "Callback fired when the open state changes" },
    { name: "disabled", type: "boolean", default: "false", description: "When true, prevents the user from interacting with the collapsible" },
  ],
  "combobox-root": [
    { name: "items", type: "T[] | GroupedItems[]", description: "The items to display. Can be a flat array or an array of groups (objects with value and items properties). Required for filtering to work." },
    { name: "openOnInputClick", type: "boolean", default: "false", description: "Whether the popup opens when clicking the input." },
    { name: "value", type: "any", description: "The controlled selected value." },
    { name: "defaultValue", type: "any", description: "The uncontrolled initial selected value." },
    { name: "onValueChange", type: "(value: any, eventDetails) => void", description: "Callback fired when the selected value changes." },
    { name: "onInputValueChange", type: "(value: string, eventDetails) => void", description: "Callback fired when the input text changes." },
    { name: "onOpenChange", type: "(open: boolean, eventDetails) => void", description: "Callback fired when the popup is opened or closed." },
    { name: "multiple", type: "boolean", default: "false", description: "Whether multiple items can be selected." },
    { name: "disabled", type: "boolean", default: "false", description: "Whether the component should ignore user interaction." },
  ],
  "combobox-item": [
    { name: "value", type: "any", description: "The value of the item. Required." },
    { name: "inset", type: "boolean", default: "false", description: "Adds extra left padding for grouped or nested option content." },
  ],
  "combobox-group": [
    { name: "items", type: "any[]", description: "Items to be rendered within this group. Child Collection components will use these items." },
  ],
  "combobox-other": [
    { name: "ComboboxContent.portal", type: "boolean", default: "true", description: "Whether to render in a portal. Set to false inside Dialog or Drawer." },
    { name: "ComboboxTrigger.children", type: "React.ReactNode", description: "Optional trigger content. Defaults to a chevron icon." },
    { name: "ComboboxClear.children", type: "React.ReactNode", description: "Optional clear action content. Defaults to an X icon." },
  ],
  "context-menu": [
    { name: "defaultOpen", type: "boolean", default: "false", description: "The initial open state when uncontrolled." },
    { name: "open", type: "boolean", description: "The controlled open state of the context menu." },
    { name: "onOpenChange", type: "(open: boolean) => void", description: "Callback fired when the open state changes." },
    { name: "loopFocus", type: "boolean", default: "true", description: "Whether to loop keyboard focus back to the first item when the end is reached." },
    { name: "disabled", type: "boolean", default: "false", description: "Whether the context menu should ignore user interaction." },
    { name: "ContextMenuItem.inset", type: "boolean", default: "false", description: "Adds indentation for nested command-style layouts." },
    { name: "ContextMenuCheckboxItem.checked", type: "boolean", description: "The controlled checked state of the checkbox item." },
    { name: "ContextMenuCheckboxItem.onCheckedChange", type: "(checked: boolean) => void", description: "Callback fired when the checkbox item is toggled." },
    { name: "ContextMenuRadioGroup.value", type: "any", description: "The controlled value of the selected radio item." },
    { name: "ContextMenuRadioGroup.onValueChange", type: "(value: any) => void", description: "Callback fired when the selected radio value changes." },
  ],
  "dialog": [
    { name: "open", type: "boolean", description: "The controlled open state of the dialog." },
    { name: "defaultOpen", type: "boolean", default: "false", description: "The initial open state for uncontrolled usage." },
    { name: "onOpenChange", type: "(open: boolean) => void", description: "Callback fired when the open state changes." },
    { name: "modal", type: "boolean | 'trap-focus'", default: "true", description: "Whether the dialog is modal. Prevents background interaction and traps focus." },
    { name: "DialogPopup.initialFocus", type: "boolean | RefObject | function", description: "Element to focus when the dialog opens." },
    { name: "DialogPopup.finalFocus", type: "boolean | RefObject | function", description: "Element to focus when the dialog closes." },
  ],
  "drawer": [
    { name: "open", type: "boolean", description: "The controlled open state of the drawer root." },
    { name: "defaultOpen", type: "boolean", default: "false", description: "The initial open state for uncontrolled usage." },
    { name: "onOpenChange", type: "(open: boolean) => void", description: "Callback fired when the drawer open state changes." },
    { name: "DrawerContent.side", type: "'top' | 'right' | 'bottom' | 'left'", default: "'right'", description: "Controls which side the drawer enters from." },
  ],
  "field": [
    { name: "name", type: "string", description: "The name of the field (required)" },
    { name: "disabled", type: "boolean", default: "false", description: "Whether the field is disabled" },
    { name: "invalid", type: "boolean", default: "false", description: "Whether the field is in an invalid state" },
    { name: "required", type: "boolean", default: "false", description: "Whether the field is required" },
    { name: "validate", type: "(value: any) => string | undefined", description: "Custom validation function that returns an error message or undefined" },
  ],
  "fieldset": [
    { name: "children", type: "React.ReactNode", description: "Field controls and optional descriptive content." },
    { name: "disabled", type: "boolean", default: "false", description: "Disables the grouped form controls when supported by child controls." },
    { name: "FieldsetLegend.children", type: "React.ReactNode", description: "Accessible label for the grouped controls." },
  ],
  "form": [
    { name: "errors", type: "Record<string, string | string[]>", description: "Validation errors returned externally, typically after submission by a server or form action." },
    { name: "onFormSubmit", type: "(values: Record<string, FormDataEntryValue>) => void", description: "Event handler receiving form values as a JavaScript object; calls preventDefault() on submit." },
    { name: "validationMode", type: "'onSubmit' | 'onBlur' | 'onChange'", default: "'onSubmit'", description: "Determines when validation occurs. Field-level setting takes precedence." },
    { name: "actionsRef", type: "RefObject<Form.Actions | null>", description: "Ref to imperative actions for programmatic validation control." },
  ],
  "input": [
    { name: "type", type: "string", default: "'text'", description: "The type of the input field" },
    { name: "placeholder", type: "string", description: "Placeholder text displayed when the input is empty" },
    { name: "disabled", type: "boolean", default: "false", description: "Whether the input is disabled" },
  ],
  "link": [
    { name: "variant", type: "'default' | 'muted' | 'plain' | 'unstyled'", default: "'default'", description: "The visual style variant of the link." },
    { name: "render", type: "ReactElement | (props, state) => ReactElement", description: "Replace the rendered <a> element with a different component (e.g., Next.js Link or React Router Link). Accepts an element or a render function." },
    { name: "external", type: "boolean", default: "false", description: "When true, adds target=\"_blank\", rel=\"noopener noreferrer\", and an external link icon." },
    { name: "href", type: "string", description: "The URL the link points to." },
    { name: "target", type: "string", default: "'_blank' when external", description: "The browsing context for the link. Defaults to \"_blank\" when external is true." },
    { name: "rel", type: "string", default: "'noopener noreferrer' when external", description: "The relationship of the linked URL. Defaults to \"noopener noreferrer\" when external is true." },
    { name: "className", type: "string", description: "Additional CSS classes to apply." },
    { name: "children", type: "React.ReactNode", description: "The link content." },
  ],
  "menu": [
    { name: "open", type: "boolean", description: "The controlled open state of the menu." },
    { name: "defaultOpen", type: "boolean", default: "false", description: "The initial open state for uncontrolled usage." },
    { name: "onOpenChange", type: "(open: boolean) => void", description: "Callback fired when the menu open state changes." },
    { name: "modal", type: "boolean", default: "true", description: "Whether the menu enters a modal state when open." },
    { name: "loopFocus", type: "boolean", default: "true", description: "Whether to loop keyboard focus back to the first item when the end is reached." },
    { name: "disabled", type: "boolean", default: "false", description: "Whether the menu should ignore user interaction." },
    { name: "MenuItem.inset", type: "boolean", default: "false", description: "Adds indentation for nested command-style layouts." },
    { name: "MenuCheckboxItem.checked", type: "boolean", description: "The controlled checked state of the checkbox item." },
    { name: "MenuCheckboxItem.onCheckedChange", type: "(checked: boolean) => void", description: "Callback fired when the checkbox item is ticked or unticked." },
    { name: "MenuRadioGroup.value", type: "any", description: "The controlled value of the selected radio item." },
    { name: "MenuRadioGroup.onValueChange", type: "(value: any) => void", description: "Callback fired when the selected radio value changes." },
    { name: "MenuRadioItem.value", type: "any", description: "Value of the radio item." },
    { name: "MenuLabel.inset", type: "boolean", default: "false", description: "Adds indentation to section labels." },
    { name: "MenuSubTrigger.inset", type: "boolean", default: "false", description: "Adds indentation to submenu triggers." },
  ],
  "menubar": [
    { name: "loopFocus", type: "boolean", default: "true", description: "Whether to loop keyboard focus back to the first item when the end is reached." },
    { name: "modal", type: "boolean", default: "true", description: "Whether the menubar is modal." },
    { name: "disabled", type: "boolean", default: "false", description: "Whether the whole menubar is disabled." },
    { name: "orientation", type: "'horizontal' | 'vertical'", default: "'horizontal'", description: "The orientation of the menubar." },
  ],
  "meter": [
    { name: "value", type: "number", description: "The current measured value." },
    { name: "min", type: "number", default: "0", description: "The minimum value of the measurement range." },
    { name: "max", type: "number", default: "100", description: "The maximum value of the measurement range." },
    { name: "MeterValue.children", type: "React.ReactNode", description: "Optional custom rendered textual value." },
  ],
  "navigation-menu": [
    { name: "value", type: "any", default: "null", description: "The controlled value of the navigation menu item that should be currently open." },
    { name: "defaultValue", type: "any", default: "null", description: "The uncontrolled value of the item that should be initially selected." },
    { name: "onValueChange", type: "(value: any) => void", description: "Callback fired when the active menu item changes." },
    { name: "delay", type: "number", default: "50", description: "How long to wait (ms) before opening the navigation menu." },
    { name: "closeDelay", type: "number", default: "50", description: "How long to wait (ms) before closing the navigation menu." },
    { name: "orientation", type: "'horizontal' | 'vertical'", default: "'horizontal'", description: "The orientation of the navigation menu." },
    { name: "NavigationMenuArrow", type: "component", description: "Renders an arrow SVG pointing towards the trigger. Place inside Popup." },
    { name: "NavigationMenuBackdrop", type: "component", description: "Renders a backdrop overlay behind the popup. Place inside Portal." },
  ],
  "number-field": [
    { name: "value", type: "number", description: "The controlled numeric value." },
    { name: "defaultValue", type: "number", description: "Initial numeric value when uncontrolled." },
    { name: "onValueChange", type: "(value: number | null) => void", description: "Callback fired when the numeric value changes." },
    { name: "min", type: "number", description: "Minimum allowed value." },
    { name: "max", type: "number", description: "Maximum allowed value." },
    { name: "step", type: "number", default: "1", description: "Increment/decrement step size." },
  ],
  "popover": [
    { name: "Popover.open", type: "boolean", description: "The controlled open state of the popover." },
    { name: "Popover.defaultOpen", type: "boolean", default: "false", description: "The initial open state when uncontrolled." },
    { name: "Popover.onOpenChange", type: "(open: boolean, event: Event) => void", description: "Callback fired when the open state changes." },
    { name: "Popover.modal", type: "boolean | 'trap-focus'", default: "false", description: "Whether the popover is modal. When true, interaction outside is blocked." },
    { name: "Popover.onOpenChangeComplete", type: "(open: boolean) => void", description: "Callback fired when open/close animation completes." },
    { name: "PopoverTrigger.openOnHover", type: "boolean", default: "false", description: "Opens the popover on hover instead of click." },
    { name: "PopoverTrigger.delay", type: "number", default: "300", description: "Milliseconds to wait before opening on hover." },
    { name: "PopoverTrigger.closeDelay", type: "number", default: "0", description: "Milliseconds to wait before closing on unhover." },
    { name: "PopoverContent.portal", type: "boolean", default: "true", description: "Whether to render in a portal. Set to false inside Dialog or Drawer." },
    { name: "PopoverContent.side", type: "'top' | 'right' | 'bottom' | 'left'", default: "'bottom'", description: "Preferred side for the popover popup." },
    { name: "PopoverContent.align", type: "'start' | 'center' | 'end'", default: "'center'", description: "Preferred alignment relative to the trigger." },
    { name: "PopoverContent.sideOffset", type: "number", default: "8", description: "Distance in pixels between trigger and popup." },
    { name: "PopoverContent.alignOffset", type: "number", description: "Additional offset along the alignment axis in pixels." },
    { name: "PopoverContent.collisionPadding", type: "number", default: "5", description: "Minimum distance from viewport edge before repositioning." },
    { name: "PopoverContent.sticky", type: "boolean", default: "false", description: "Keep the popover visible when the anchor scrolls out of view." },
  ],
  "preview-card": [
    { name: "PreviewCard.open", type: "boolean", description: "The controlled open state of the preview card" },
    { name: "PreviewCard.defaultOpen", type: "boolean", default: "false", description: "The initial open state when uncontrolled" },
    { name: "PreviewCard.onOpenChange", type: "(open: boolean, event: Event) => void", description: "Callback fired when the open state changes" },
    { name: "PreviewCard.onOpenChangeComplete", type: "(open: boolean) => void", description: "Callback fired when open/close animation completes" },
    { name: "PreviewCardTrigger.delay", type: "number", default: "600", description: "Milliseconds to wait before the preview card opens on hover" },
    { name: "PreviewCardTrigger.closeDelay", type: "number", default: "300", description: "Milliseconds to wait before the preview card closes on unhover" },
    { name: "PreviewCardPositioner.side", type: "'top' | 'right' | 'bottom' | 'left' | 'inline-start' | 'inline-end'", default: "'bottom'", description: "The preferred side of the trigger to render the preview card" },
    { name: "PreviewCardPositioner.sideOffset", type: "number", default: "8", description: "The distance in pixels from the trigger" },
    { name: "PreviewCardPositioner.align", type: "'start' | 'center' | 'end'", default: "'center'", description: "Alignment along the trigger edge" },
    { name: "PreviewCardPositioner.collisionPadding", type: "number", default: "5", description: "Minimum distance from viewport edge before repositioning" },
  ],
  "progress": [
    { name: "value", type: "number", description: "The current progress value." },
    { name: "max", type: "number", default: "100", description: "The maximum value that represents full completion." },
    { name: "getValueLabel", type: "(value: number, max: number) => string", description: "Optional formatter for accessible progress value text." },
  ],
  "radio": [
    { name: "RadioGroup.value", type: "string", description: "The controlled selected radio value." },
    { name: "RadioGroup.defaultValue", type: "string", description: "The initially selected value when uncontrolled." },
    { name: "RadioGroup.onValueChange", type: "(value: string, event: Event) => void", description: "Callback fired when the selected value changes." },
    { name: "RadioGroup.name", type: "string", description: "Identifies the field when a form is submitted." },
    { name: "RadioGroup.disabled", type: "boolean", default: "false", description: "Disables all radio options in the group." },
    { name: "RadioGroup.readOnly", type: "boolean", default: "false", description: "Prevents the user from selecting a different radio." },
    { name: "RadioGroup.required", type: "boolean", default: "false", description: "Requires a value before submitting a form." },
    { name: "Radio.value", type: "string", description: "The unique identifying value of the radio in a group." },
    { name: "Radio.disabled", type: "boolean", default: "false", description: "Disables a radio option." },
    { name: "RadioIndicator.keepMounted", type: "boolean", default: "false", description: "Keeps the indicator in the DOM when the radio is inactive." },
  ],
  "scroll-area": [
    { name: "ScrollAreaScrollbar.orientation", type: "'vertical' | 'horizontal'", default: "'vertical'", description: "Sets scrollbar orientation." },
    { name: "type", type: "'hover' | 'scroll' | 'auto' | 'always'", default: "'hover'", description: "Controls when scrollbars are visible." },
    { name: "scrollHideDelay", type: "number", default: "600", description: "Delay before auto-hidden scrollbars are hidden again." },
  ],
  "select": [
    { name: "value", type: "string", description: "The controlled selected value." },
    { name: "defaultValue", type: "string", description: "The initially selected value when uncontrolled." },
    { name: "onValueChange", type: "(value: string) => void", description: "Callback fired when selection changes." },
    { name: "SelectContent.portal", type: "boolean", default: "true", description: "Whether to render the dropdown in a portal. Set to false when used inside a Dialog or Drawer to keep it within the modal focus trap." },
    { name: "SelectContent.alignItemWithTrigger", type: "boolean", default: "false", description: "Overlaps the trigger to align the selected item text with the trigger value." },
    { name: "SelectContent.sideOffset", type: "number", default: "4", description: "Distance between trigger and popup." },
    { name: "SelectItem.showIndicator", type: "boolean", default: "false", description: "Shows a check icon for the selected item." },
  ],
  "separator": [
    { name: "orientation", type: "'horizontal' | 'vertical'", default: "'horizontal'", description: "Sets the separator orientation." },
    { name: "decorative", type: "boolean", default: "true", description: "Whether the separator is decorative only." },
  ],
  "skeleton": [
    { name: "className", type: "string", description: "Classes to control size, shape, and border radius of the skeleton." },
  ],
  "label": [
    { name: "htmlFor", type: "string", description: "The id of the form element this label is associated with." },
    { name: "className", type: "string", description: "Additional classes for custom styling." },
  ],
  "slider": [
    { name: "value", type: "number[]", description: "The controlled value of the slider" },
    { name: "defaultValue", type: "number[]", description: "The default value when uncontrolled" },
    { name: "onValueChange", type: "(value: number[]) => void", description: "Callback fired when the slider value changes" },
    { name: "min", type: "number", default: "0", description: "The minimum allowed value" },
    { name: "max", type: "number", default: "100", description: "The maximum allowed value" },
    { name: "step", type: "number", default: "1", description: "The step increment between values" },
    { name: "disabled", type: "boolean", default: "false", description: "Whether the slider is disabled" },
    { name: "orientation", type: "'horizontal' | 'vertical'", default: "'horizontal'", description: "The orientation of the slider" },
  ],
  "switch": [
    { name: "checked", type: "boolean", description: "The controlled checked state" },
    { name: "defaultChecked", type: "boolean", default: "false", description: "The initial checked state when uncontrolled" },
    { name: "onCheckedChange", type: "(checked: boolean, details: object) => void", description: "Callback fired when checked state changes" },
    { name: "name", type: "string", description: "Identifies the field when a form is submitted" },
    { name: "value", type: "string", description: "Value submitted when switch is on (defaults to 'on')" },
    { name: "disabled", type: "boolean", default: "false", description: "Disables the switch" },
    { name: "readOnly", type: "boolean", default: "false", description: "Prevents activation and deactivation" },
    { name: "required", type: "boolean", default: "false", description: "Marks the switch as required in a form" },
  ],
  "tabs": [
    { name: "defaultValue", type: "string", description: "The value of the tab to select by default" },
    { name: "value", type: "string", description: "The controlled value of the currently active tab" },
    { name: "onValueChange", type: "(value: string) => void", description: "Callback fired when the active tab changes" },
  ],
  "toast": [
    { name: "Toast.limit", type: "number", default: "3", description: "Maximum number of visible toasts" },
    { name: "Toast.timeout", type: "number", default: "5000", description: "Auto-dismiss timeout in milliseconds. Use 0 to prevent auto-dismiss." },
    { name: "Toast.toastManager", type: "ToastManager", description: "External toast manager created via createToastManager() for global usage" },
    { name: "Toast.renderToast", type: "(toast: ToastObject) => ReactNode", description: "Custom render function for toasts. Receives the toast object and returns JSX. Falls back to the default layout when not provided." },
    { name: "ToastRoot.variant", type: "'default' | 'destructive' | 'success' | 'warning' | 'loading'", default: "'default'", description: "The visual style variant of the toast" },
    { name: "ToastRoot.toast", type: "ToastObject", description: "The toast data object from the manager (required)" },
    { name: "ToastRoot.swipeDirection", type: "Array<'up' | 'down' | 'left' | 'right'>", default: "['down', 'right']", description: "The directions in which the toast can be swiped to dismiss" },
    { name: "ToastList.renderToast", type: "(toast: ToastObject) => ReactNode", description: "Custom render function for toasts. Same as Toast.renderToast but applied directly to ToastList." },
    { name: "ToastClose.children", type: "ReactNode", description: "Custom close icon. Renders an XIcon from lucide-react by default." },
    { name: "ToastPositioner.toast", type: "ToastObject", description: "The toast data object (required). Positions the toast relative to an anchor element." },
    { name: "ToastPositioner.anchor", type: "Element | null", description: "The element to anchor the toast to." },
    { name: "ToastPositioner.side", type: "'top' | 'bottom' | 'left' | 'right' | 'inline-end' | 'inline-start'", default: "'top'", description: "Which side of the anchor to position the toast on." },
    { name: "ToastPositioner.align", type: "'start' | 'center' | 'end'", default: "'center'", description: "Alignment along the anchor edge." },
    { name: "ToastPositioner.sideOffset", type: "number", default: "0", description: "Distance in pixels from the anchor." },
    { name: "ToastArrow.className", type: "string", description: "Additional classes for the decorative arrow. Styled with directional data-side attributes." },
    { name: "manager.add()", type: "(options: { title?, description?, type?, timeout?, actionProps?, data?, priority? }) => string", description: "Creates a toast notification and returns its ID" },
    { name: "manager.update()", type: "(id: string, updates) => void", description: "Updates an existing toast's title, description, type, timeout, or actionProps" },
    { name: "manager.close()", type: "(id?: string) => void", description: "Closes a toast by its ID, or dismisses all toasts when called with no arguments" },
    { name: "manager.promise()", type: "(promise, { loading, success, error }) => Promise", description: "Binds a promise to a toast that auto-transitions through loading, success, and error states" },
    { name: "manager.subscribe()", type: "(listener: () => void) => () => void", description: "Observes toast state changes. Returns an unsubscribe function." },
  ],
  "text": [
    { name: "variant", type: "'h1' | 'h2' | 'h3' | 'h4' | 'p' | 'large' | 'small' | 'lead' | 'muted' | 'blockquote' | 'code' | 'span'", default: "'p'", description: "The typography style variant. Determines both visual styling and the rendered HTML element." },
    { name: "as", type: "React.ElementType", description: "Override the default HTML element. For example, render an h2-styled element as an <h3>." },
    { name: "className", type: "string", description: "Additional CSS classes to apply." },
    { name: "children", type: "React.ReactNode", description: "The text content to render." },
  ],
  "toggle-group": [
    { name: "multiple", type: "boolean", default: "false", description: "When true, multiple items can be pressed simultaneously" },
    { name: "value", type: "string[]", description: "Controlled array of pressed toggle values" },
    { name: "defaultValue", type: "string[]", description: "Initial pressed values for uncontrolled usage" },
    { name: "onValueChange", type: "(groupValue: string[], details: object) => void", description: "Callback fired when selection changes" },
    { name: "orientation", type: "'horizontal' | 'vertical'", default: "'horizontal'", description: "The orientation of the toggle group" },
    { name: "loopFocus", type: "boolean", default: "true", description: "Whether keyboard navigation should loop from last to first and vice versa" },
    { name: "disabled", type: "boolean", default: "false", description: "Whether the entire toggle group is disabled" },
    { name: "ToggleGroupItem.variant", type: "'default' | 'outline'", default: "'outline'", description: "Visual style variant for each item" },
    { name: "ToggleGroupItem.size", type: "'default' | 'sm' | 'lg'", default: "'sm'", description: "Size variant for each item" },
  ],
  "toggle": [
    { name: "variant", type: "'default' | 'outline'", default: "'default'", description: "The visual style variant of the toggle" },
    { name: "size", type: "'default' | 'sm' | 'lg'", default: "'default'", description: "The size of the toggle" },
    { name: "pressed", type: "boolean", description: "The controlled pressed state of the toggle" },
    { name: "defaultPressed", type: "boolean", default: "false", description: "The default pressed state when uncontrolled" },
    { name: "onPressedChange", type: "(pressed: boolean, details: object) => void", description: "Callback fired when the pressed state changes" },
    { name: "value", type: "string", description: "Identifies the toggle when used inside a ToggleGroup" },
    { name: "disabled", type: "boolean", default: "false", description: "Whether the toggle is disabled" },
  ],
  "toolbar": [
    { name: "orientation", type: "'horizontal' | 'vertical'", default: "'horizontal'", description: "The orientation of the toolbar" },
    { name: "loopFocus", type: "boolean", default: "true", description: "Whether keyboard navigation should loop from last to first and vice versa" },
    { name: "disabled", type: "boolean", default: "false", description: "Whether the entire toolbar is disabled" },
  ],
  "tooltip": [
    { name: "variant", type: "'default' | 'inverse'", default: "'default'", description: "The visual style variant of the tooltip" },
    { name: "openDelay", type: "number", default: "700", description: "The delay in milliseconds before the tooltip opens" },
    { name: "closeDelay", type: "number", default: "300", description: "The delay in milliseconds before the tooltip closes" },
    { name: "side", type: "'top' | 'right' | 'bottom' | 'left'", default: "'top'", description: "The preferred side of the trigger to render the tooltip" },
    { name: "sideOffset", type: "number", default: "4", description: "The distance in pixels from the trigger" },
    { name: "showArrow", type: "boolean", default: "true", description: "Whether to show the tooltip arrow pointing to the trigger" },
    { name: "TooltipTrigger.closeOnClick", type: "boolean", default: "true", description: "Whether clicking the trigger dismisses the tooltip. Set to false to keep the tooltip open on click." },
  ],
};
